/* 机构名录，手工策展（本文件不被构建覆盖）。
 * 六类分列：公司 / 高校与实验室 / 研究机构 / 非营利与治理 / 资本 / 媒体与数据。
 * k 为语料匹配关键词：前台对线索、大事记、档案做提及计数（非严格归属，量级参考）。 */
DB.orgs = {
  groups: [
    { key: 'companies', name: '公司', en: 'Companies', desc: '模型、算力、应用与工具的主要公司法人与产品主体。', items: [
      { n: 'OpenAI', d: '前沿 lab + 消费入口，行业叙事定义者', k: ['openai', 'chatgpt', 'gpt'] },
      { n: 'Anthropic', d: 'Claude 系，编码/Agent 最强卖方', k: ['anthropic', 'claude'] },
      { n: 'Google DeepMind', d: 'Gemini 全家桶 + 机器人 + 科学 AI', k: ['deepmind', 'gemini'] },
      { n: 'Meta', d: '开源 Llama 路线与超级智能 lab', k: ['meta', 'llama'] },
      { n: 'Microsoft', d: 'Copilot 生态 + MAI 自研模型', k: ['microsoft', 'copilot', 'azure'] },
      { n: 'NVIDIA', d: '算力垄断者：芯片 + 网络 + CUDA', k: ['nvidia', '英伟达'] },
      { n: 'xAI（SpaceXAI）', d: 'Grok 系 + SpaceX 资源整合', k: ['xai', 'grok', 'spacexai'] },
      { n: 'Amazon', d: 'AWS + 反向收购补 AI 能力', k: ['amazon', 'aws'] },
      { n: 'Apple', d: '端侧 AI 与隐私路线', k: ['apple', '苹果'] },
      { n: 'DeepSeek', d: '开源高性价比破局者', k: ['deepseek', '深度求索'] },
      { n: '阿里通义', d: 'Qwen 开源 + 百炼云', k: ['qwen', '通义', '阿里'] },
      { n: '智谱', d: 'GLM 开源 + 激进定价', k: ['glm', '智谱'] },
      { n: '月之暗面', d: 'Kimi 消费入口 + 融资争议样本', k: ['kimi', '月之暗面', 'moonshot'] },
      { n: 'MiniMax', d: '全模态与视频生成开源', k: ['minimax', 'hailuo'] },
      { n: '腾讯混元', d: '大厂开源转向样本', k: ['混元', 'hunyuan'] },
      { n: '字节跳动 Seed', d: 'Seedance 视频 + 豆包生态', k: ['seedance', '豆包', 'seed'] },
      { n: '百度文心', d: '文心 + 昆仑芯全栈', k: ['文心', 'ernie', '百度'] },
      { n: '商汤', d: '视觉起家的大模型转型', k: ['商汤', 'sensetime'] },
      { n: 'Mistral', d: '欧洲开源旗舰，地缘即模式', k: ['mistral'] },
      { n: 'Cohere', d: '企业级 RAG 与北美元老', k: ['cohere'] },
      { n: 'Hugging Face', d: '开源社区基础设施（NVIDIA 收购）', k: ['hugging face', 'huggingface', 'hf'] },
      { n: 'Cursor（Anysphere）', d: 'AI IDE 标杆，SpaceX 全资子公司', k: ['cursor', 'anysphere'] },
      { n: 'Perplexity', d: '答案引擎代表', k: ['perplexity'] },
      { n: 'Midjourney', d: '图像生成独立头部', k: ['midjourney'] },
      { n: 'Runway', d: '视频生成头部', k: ['runway'] },
      { n: 'Suno', d: 'AI 音乐与版权诉讼中心', k: ['suno'] },
      { n: '宇树科技', d: '人形机器人第一股', k: ['宇树', 'unitree'] },
      { n: 'Figure AI', d: '人形机器人美系代表', k: ['figure'] },
      { n: 'Scale AI', d: '数据供应链枢纽', k: ['scale ai', 'scaleai'] },
      { n: 'CoreWeave', d: '算力租赁标杆', k: ['coreweave'] },
      { n: 'Together AI', d: '开源模型托管平台', k: ['together'] },
      { n: 'Databricks', d: '数据平台 + 自研模型', k: ['databricks'] }
    ]},
    { key: 'univ', name: '高校与实验室', en: 'Universities', desc: '学术研究的源点：论文、人才与开源项目的孵化地。', items: [
      { n: 'Stanford HAI', d: 'AI 指数与政策研究重镇', k: ['stanford', 'hai'] },
      { n: 'MIT CSAIL', d: 'AI 实验室活化石', k: ['mit', 'csail'] },
      { n: 'UC Berkeley（BAIR）', d: 'vLLM/SGLang/Arena 的学术源点', k: ['berkeley', 'bair', 'lmsys'] },
      { n: 'CMU', d: '机器人学与 NLP 重镇', k: ['cmu', '卡内基'] },
      { n: 'University of Toronto / Vector', d: '深度学习发源地之一', k: ['toronto', 'vector'] },
      { n: 'Mila（蒙特利尔）', d: 'Bengio 的实验室', k: ['mila', 'bengio'] },
      { n: 'Oxford FHI', d: 'AI 安全哲学传统', k: ['oxford', 'fhi', 'bostrom'] },
      { n: 'Cambridge（Leverhulme CFI）', d: 'AI 伦理与治理研究', k: ['cambridge', '剑桥'] },
      { n: '清华大学（AIR）', d: '国产 AI 人才与基础研究核心', k: ['清华'] },
      { n: '北京大学', d: '语言与计算基础研究', k: ['北大', '北京大学的'] },
      { n: '上海交通大学', d: '推理与系统研究', k: ['上海交通'] },
      { n: '浙江大学', d: '计算机视觉重镇', k: ['浙大', '浙江大学的'] },
      { n: '中国科学技术大学', d: '语音与认知研究', k: ['中科大', '中国科学技术大学'] },
      { n: 'ETH Zurich', d: '欧洲系统与安全研究', k: ['eth', '苏黎世'] },
      { n: 'NYU', d: 'LeCun 系深度学习传统', k: ['nyu', 'lecun'] },
      { n: 'KAIST / 首尔大学', d: '韩国 AI 国家队', k: ['kaist', '首尔大学'] }
    ]},
    { key: 'labs', name: '研究机构', en: 'Research Institutes', desc: '企业外或企业内的独立研究组织与国家级实验室。', items: [
      { n: 'AI2（Allen Institute）', d: '开放科学与 OLMo 系列', k: ['ai2', 'allen'] },
      { n: 'FAIR（Meta AI 研究院）', d: '基础研究引擎', k: ['fair'] },
      { n: 'MSRA（微软亚洲研究院）', d: '中国 AI 黄埔军校', k: ['msra', '微软亚洲研究院'] },
      { n: '阿里达摩院', d: '阿里巴巴基础研究机构', k: ['达摩院'] },
      { n: '腾讯 AI Lab', d: '腾讯基础研究线', k: ['腾讯 ai lab', 'ai lab'] },
      { n: '上海人工智能实验室', d: '国家级实验室，书生/InternLM', k: ['上海人工智能实验室', 'internlm', '书生'] },
      { n: '北京智源研究院（BAAI）', d: '悟道系列与开源生态', k: ['智源', 'baai', '悟道'] },
      { n: '之江实验室', d: '浙江国家级实验室', k: ['之江实验室'] },
      { n: '鹏城实验室', d: '深圳国家级实验室，鹏城云脑', k: ['鹏城', 'pengcheng'] },
      { n: '智谱-清华联合实验室', d: 'GLM 的学术源头', k: ['智谱清华', '联合实验室'] },
      { n: 'Google Research', d: '跨学科基础研究', k: ['google research'] },
      { n: 'RAND Corporation', d: 'AI 政策与安全评估传统', k: ['rand'] }
    ]},
    { key: 'orgs', name: '非营利与治理', en: 'Nonprofits & Governance', desc: '安全研究、标准制定与监管执行的中立机构。', items: [
      { n: 'MIRI', d: 'AI 对齐理论最早的非营利', k: ['miri'] },
      { n: 'FLI（未来生命研究所）', d: '暂停巨型 AI 公开信发起方', k: ['fli', '未来生命研究所'] },
      { n: 'CAIS', d: 'AI 安全中心，风险声明起草方', k: ['cais', 'ai 安全中心'] },
      { n: 'AI Now Institute', d: 'AI 社会影响研究', k: ['ai now'] },
      { n: 'EFF', d: '数字权利与算法问责', k: ['eff', '电子前哨'] },
      { n: 'NIST（AI 安全研究所）', d: '美国标准与评估框架', k: ['nist'] },
      { n: 'UK AISI', d: '英国 AI 安全研究所，前沿评测', k: ['aisi', '英国 ai 安全'] },
      { n: 'EU AI Office', d: '欧盟 AI Act 执行机构', k: ['ai office', 'ai act 执法', '欧盟委员会'] },
      { n: 'OECD AI Policy Observatory', d: '跨国政策数据库', k: ['oecd'] },
      { n: '中国信通院', d: '标准与产业政策研究', k: ['信通院', 'caict'] },
      { n: '联合国 AI 咨询机构', d: '全球治理协调', k: ['联合国'] },
      { n: '全国网安标委（TC260）', d: '国内 AI 安全标准制定', k: ['tc260', '网安标委'] }
    ]},
    { key: 'funds', name: '资本', en: 'Capital', items: [
      { n: 'a16z', d: 'AI 全栈下注的头部 VC', k: ['a16z', 'andreessen'] },
      { n: 'Sequoia', d: '长期头部（红杉美/中双线）', k: ['sequoia', '红杉'] },
      { n: 'Thrive Capital', d: 'OpenAI 关键外部股东', k: ['thrive'] },
      { n: 'Accel', d: 'Anysphere/Cursor 早期投资方', k: ['accel'] },
      { n: 'Founders Fund', d: '硬科技与 AI 基础设施', k: ['founders fund'] },
      { n: 'SoftBank Vision Fund', d: '超级轮的主要出资方', k: ['softbank', '孙正义'] },
      { n: 'Tiger Global', d: '成长轮常客', k: ['tiger global'] },
      { n: 'Coatue', d: '科技对冲 + 一级', k: ['coatue'] },
      { n: 'Lightspeed', d: '应用层早期活跃', k: ['lightspeed', '光速'] },
      { n: 'Index Ventures', d: '欧洲与平台层', k: ['index ventures'] },
      { n: '高瓴 / 高瓴创投', d: '国内头部（月之暗面等）', k: ['高瓴'] },
      { n: '深创投', d: '国资背景头部', k: ['深创投'] },
      { n: '中金资本', d: '券商系 PE', k: ['中金资本'] },
      { n: '上海国投/国资产业基金', d: '地方引导基金样本', k: ['国资', '引导基金'] },
      { n: 'MGX（阿布扎比）', d: '中东主权资本入场', k: ['mgx', '阿布扎比'] },
      { n: 'Temasek / GIC', d: '新加坡主权资本', k: ['temasek', 'gic', '淡马锡'] }
    ]},
    { key: 'media', name: '媒体与数据', en: 'Media & Data', items: [
      { n: 'The Information', d: '科技商业深度报道标杆', k: ['the information'] },
      { n: 'TechCrunch', d: '创业与融资快讯', k: ['techcrunch'] },
      { n: 'Reuters', d: '并购与政策一手信源', k: ['reuters', '路透'] },
      { n: 'Bloomberg', d: '财经与算力资本开支', k: ['bloomberg', '彭博'] },
      { n: 'IT之家', d: '国内快讯主力信源', k: ['it之家'] },
      { n: '机器之心', d: '技术与模型深度', k: ['机器之心'] },
      { n: '量子位', d: '产业与技术混合报道', k: ['量子位'] },
      { n: '新智元', d: 'AI 资讯聚合', k: ['新智元'] },
      { n: 'Hacker News', d: '开发者风向与开源热点', k: ['hacker news'] },
      { n: 'arXiv / Hugging Face Papers', d: '论文沉淀与检索入口', k: ['arxiv'] }
    ]}
  ]
};
